package graphic;

import java.io.IOException;
import java.net.InetAddress;
import java.net.MulticastSocket;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *          
 * @author jonat
 */
public class ChatFrame extends javax.swing.JFrame {

    static String Usuario;
    static MulticastSocket ms;
    static int pt = 8001;
    static String dir = "235.23.13.21";
    static InetAddress gpo = null;
    ArrayList<Unicode> unicodes = new ArrayList<>();
    public DefaultListModel model = new DefaultListModel();
    
    //enviarImagen se activia con el botón
    RecibirImagen recibidoImg;

    //Thread envio = new EnviarImagen();
    //RecibirImagen recibido = new RecibirImagen();
    //Thread recibido=new RecibirImagen();
    /**
     * Creates new form Frame0
     */
    public ChatFrame() {
        initComponents();

        int randomNum = ThreadLocalRandom.current().nextInt(1, 12 + 1);
        while (Usuario == null) {
            Usuario = JOptionPane.showInputDialog("Bienvenido, tu alias para el chat es:", "nickname" + randomNum);
        }
        System.out.println(Usuario);

        
        recibidoImg = new RecibirImagen(this.jPrgBrSending, this.mensajesPane, Usuario);
        
        lblUser.setText(Usuario);

        try {
            ms = new MulticastSocket(pt);
            ms.setReuseAddress(true);
            ms.setTimeToLive(255);
            try {
                gpo = InetAddress.getByName(dir);
            } catch (UnknownHostException e) {
                System.out.println("Direccion Multicast no valida");
                ms.close();
                System.exit(1);
            }
            ms.joinGroup(gpo);
            System.out.println("Servicio iniciado y unido al grupo: " + dir);

        } catch (IOException e) {
        }

        jPrgBrSending.setStringPainted(true);
        
        unicodes.add(new Unicode("&#9733;", "estrella", "star"));
        unicodes.add(new Unicode("&#1F1EB;", "phone", "tel"));
        unicodes.add(new Unicode("&#9748;", "sombrilla", "sombrilla"));
        unicodes.add(new Unicode("&#9749", "cafe", "cafe"));
        unicodes.add(new Unicode("&#9785", "cara", ":\\("));
        unicodes.add(new Unicode("&#9786", "cara", ":\\)"));
        unicodes.add(new Unicode("&#9788", "sol", "sol"));
        unicodes.add(new Unicode("&#9790", "sol", "luna"));
        unicodes.add(new Unicode("&#9917", "pelota", "futbol"));
        unicodes.add(new Unicode("&#9835", "nota", "musica"));
        unicodes.add(new Unicode("&#9925", "nube", "nublado"));
        unicodes.add(new Unicode("&#9973", "bote", "barco"));
        unicodes.add(new Unicode("&#9973", "bote", "barco"));
        
        
        iniciarRecibir();
        recibidoImg.start();//for the image
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        lblUser = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensajesPane = new HTMLpane();
        jCmbConectados = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTxtFieldMsj = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPrgBrSending = new javax.swing.JProgressBar();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chat multicast");
        setBackground(new java.awt.Color(204, 153, 255));
        setForeground(new java.awt.Color(204, 153, 255));

        lblUser.setBackground(new java.awt.Color(153, 255, 153));
        lblUser.setFont(new java.awt.Font("Roboto Mono", 2, 16)); // NOI18N
        lblUser.setText("user¿?");

        jLabel4.setFont(new java.awt.Font("Roboto Mono", 2, 14)); // NOI18N
        jLabel4.setText("Iniciado como:");

        mensajesPane.setBackground(new java.awt.Color(255, 204, 204));
        jScrollPane1.setViewportView(mensajesPane);

        jCmbConectados.setBackground(new java.awt.Color(153, 153, 255));
        jCmbConectados.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jLabel2.setText("Conectados ");

        jButton3.setBackground(new java.awt.Color(204, 255, 102));
        jButton3.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jButton3.setText("Chat");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTxtFieldMsj.setBackground(new java.awt.Color(204, 255, 255));
        jTxtFieldMsj.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTxtFieldMsj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFieldMsjActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/sent-mail.png"))); // NOI18N
        jButton4.setText("Enviar");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Roboto Mono", 0, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/photo-camera.png"))); // NOI18N
        jButton6.setText("Foto");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jPrgBrSending.setBackground(new java.awt.Color(51, 255, 102));
        jPrgBrSending.setForeground(new java.awt.Color(0, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTxtFieldMsj, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addGap(18, 18, 18)
                            .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jCmbConectados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(59, 59, 59))))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPrgBrSending, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblUser))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmbConectados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4)
                            .addComponent(jTxtFieldMsj)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPrgBrSending, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (!jTxtFieldMsj.getText().equalsIgnoreCase("")) {
            Calendar calendario = Calendar.getInstance();
            int horaH = calendario.get(Calendar.HOUR_OF_DAY);
            int min = calendario.get(Calendar.MINUTE);
            int sec = calendario.get(Calendar.SECOND);
            String hora = String.valueOf(horaH + ":" + min + ":" + sec);
            String mensaje = jTxtFieldMsj.getText();

            Mensaje M = new Mensaje(Usuario, hora, mensaje, "publico");

            //for(int i=0;i<2;i++){
            Thread enviar = new Enviar("Enviar", mensajesPane, ms, gpo, pt, M);
            enviar.start();
            //}

            jTxtFieldMsj.setText("");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTxtFieldMsjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFieldMsjActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTxtFieldMsjActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (jCmbConectados.getSelectedIndex() != -1) {
            String usuarioDestinatario = jCmbConectados.getSelectedItem().toString();

            Calendar calendario = Calendar.getInstance();
            int horaH = calendario.get(Calendar.HOUR_OF_DAY);
            int min = calendario.get(Calendar.MINUTE);
            int sec = calendario.get(Calendar.SECOND);
            String hora = String.valueOf(horaH + ":" + min + ":" + sec);

            System.out.println("Usuario: " + Usuario);
            System.out.println("Destinatario: " + usuarioDestinatario);

            Mensaje MP = new Mensaje(Usuario, hora, "", usuarioDestinatario, "conectar");

            Thread enviar = new Enviar("Enviar", ms, gpo, pt, MP);
            enviar.start();

            ChatPrivado_Frame CP = new ChatPrivado_Frame(usuarioDestinatario, Usuario, ms, gpo, pt);
            CP.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        EnviarImagen envioImg;
        envioImg = new EnviarImagen(Usuario);
        envioImg.start();
        //envioImg.join();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void iniciarRecibir() {
        Thread recibir = new Recibir("RecibirPublico", mensajesPane, Usuario, ms, gpo, pt, jCmbConectados);
        recibir.start();

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jCmbConectados;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JProgressBar jPrgBrSending;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTxtFieldMsj;
    private javax.swing.JLabel lblUser;
    /*
    private javax.swing.JTextPane mensajesPane;
    */
    HTMLpane mensajesPane;
    // End of variables declaration//GEN-END:variables
}
